### ISSUE TITLE
A2F: Transform constants from Autosar to Franca

### ISSUE THREAD

**Issue by MLanghammer** [GENIVI/franca_ara_tools#111]

**Comment by MLanghammer** [comment]
Since we do not really know what to do here from Autosar to Franca side this ticket is closed. If at some point in time we know what to do we will impelement it.

**Comment by TorstenGoerg** [comment]
This ticket is reopened because some aspects on the AUTORSAR to Franca conversion of constant definitions can be done.
But the possibilities are limited, i.e., because constant definitions are just roughly typed in the AUTOSAR representation. Due to this limitation, detailed types of constants can only be partly derived from AUTOSAR models. I.e., it is not possible to guess references to named type definitions. Instead, we generate new artifical type definitions for complex types in the target Franca models.
